### ISSUE TITLE
请问KL散度中的p分布计算方式如何理解？

### ISSUE THREAD

**Issue by Hydraz320** [XifengGuo/DCEC#1]
论文中说了p的计算是依赖于q，按照我自己的理解，p应该是真实分布，为什么用q去计算可行呢？以及公式8对p的计算方法的依据是什么？期待回答

**Comment by Hydraz320** [comment]
我看了DEC的论文 并不是很明白。。。

**Comment by XifengGuo** [comment]
通过将属于同一个类的样本变得更紧凑，有助于获得更好的聚类性能。为了达到这个目的，就可以根据q来计算一个目标分布p，在p这个分布下的样本就具有‘更紧凑’的性质。因为qij表示样本i属于聚类j的概率，那么平方之后再归一化得到的pij就对qij进行了增强，即如果qij比较大，那么pij就更大，对应的样本i就距离类j更近。

**Comment by Hydraz320** [comment]
非常感谢！！我大致明白了 这就是为什么有的论文里会说这是一种自学习或者自训练。它会对已有的聚类结果有着增强作用。

**Comment by Hydraz320** [comment]
还有个问题想请教下 请问您有没有在除了mnist数据集和USPS以外的数据集上测试过这个网络？我尝试着在STL-10上进行训练 但是loss的收敛情况有些不理想。如果进行参数调整的话 单单增加各层filter数量和中间隐藏层的encode数可以吗？
