### ISSUE TITLE
How do you visualize clustering results.

### ISSUE THREAD

**Issue by TrsNium** [XifengGuo/DCEC#2]
I read your paper works.
I seems that this work was so interesting.
I'm planning to apply in the field of natural language processing.

However, I'm not sure to how to visualize clustering results like yours .

**Comment by XifengGuo** [comment]
@TrsNium Use T-SNE. http://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html

**Comment by TrsNium** [comment]
ok, thanks
