### ISSUE TITLE
Huge data-set On GPU

### ISSUE THREAD

**Issue by amir-sha** [XifengGuo/DCEC#3]
is there a way to run your code on GPU? because my data set is over 1000000 images and takes forever to run on CPU

**Comment by XifengGuo** [comment]
@nnowaker The code is default run on GPU if available. Maybe you didn't configure keras and tensorflow correctly? Make sure you have installed tensorflow by `pip install tensorflow-gpu` instead of `pip install tensorflow`.

**Comment by amir-sha** [comment]
thanks a lot problem solved , Now each epoch is only 3 secs insted of 35 secs !
