### ISSUE TITLE
Error when replicating on Conv3D model

### ISSUE THREAD

**Issue by MaryleenAmaizu** [XifengGuo/DCEC#4]
I try to replicate this code on Conv3D and I get error about the input dimension. I already modified the input shape for the 3D ConvNet and it seems this has to do with the clustering hidden layer. I am at a loss on where to rework the code to get it running.

`Layer (type)                 Output Shape              Param #   
=================================================================
conv3d_19 (Conv3D)           (None, 55, 55, 10, 128)   15616     
_________________________________________________________________
conv3d_20 (Conv3D)           (None, 26, 26, 10, 64)    204864    
_________________________________________________________________
embedding (ConvLSTM2D)       (None, 26, 26, 10, 64)    295168    
_________________________________________________________________
conv_lst_m2d_9 (ConvLSTM2D)  (None, 26, 26, 10, 32)    110720    
_________________________________________________________________
conv_lst_m2d_10 (ConvLSTM2D) (None, 26, 26, 10, 64)    221440    
_________________________________________________________________
conv3d_transpose_9 (Conv3DTr (None, 55, 55, 10, 128)   204928    
_________________________________________________________________
conv3d_transpose_10 (Conv3DT (None, 227, 227, 10, 1)   15489     
=================================================================
Total params: 1,068,225
Trainable params: 1,068,225
Non-trainable params: 0
_________________________________________________________________
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-4628dbdb79de> in <module>()
     81 
     82     # prepare the DCEC model
---> 83     dcec = DCEC(input_shape=(227,227,10,1), n_clusters=n_clusters)
     84     plot_model(dcec.model, to_file= save_dir + '/dcec_model.png', show_shapes=True)
     85     dcec.model.summary()
<ipython-input-23-a0c0461ae64e> in __init__(self, input_shape, n_clusters, alpha)
     80 
     81        # Define DCEC model
---> 82        clustering_layer = ClusteringLayer(self.n_clusters, name='clustering')(hidden)
     83        self.model = Model(inputs=self.cae.input,
     84                           outputs=[clustering_layer, self.cae.output])
~\Anaconda2\envs\py36\lib\site-packages\keras\engine\base_layer.py in __call__(self, inputs, **kwargs)
    441             # Raise exceptions in case the input is not compatible
    442             # with the input_spec set at build time.
--> 443             self.assert_input_compatibility(inputs)
    444 
    445             # Handle mask propagation.
~\Anaconda2\envs\py36\lib\site-packages\keras\engine\base_layer.py in assert_input_compatibility(self, inputs)
    309                                      self.name + ': expected ndim=' +
    310                                      str(spec.ndim) + ', found ndim=' +
--> 311                                      str(K.ndim(x)))
    312             if spec.max_ndim is not None:
    313                 ndim = K.ndim(x)
ValueError: Input 0 is incompatible with layer clustering: expected ndim=2, found ndim=5`

**Comment by XifengGuo** [comment]
@Maryleen The `ClusteringLayer` only supports 2-dimensional input and output tensors. So you have to add a Flatten layer before and a Reshape layer after it.
