### ISSUE TITLE
Results on STL10

### ISSUE THREAD

**Issue by leo2105** [XifengGuo/DCEC#6]
Hi, Nice work!
I would like to know if you tried and get some results on dataset STL10.
Thanks

**Comment by XifengGuo** [comment]
@leo2105 No. If input pixel-level representation of STL10, the result can be very bad due to the poor ability of autoencoder to learn semantic features

**Comment by vivektreddy** [comment]
Hi, great paper!
I am wondering if it would be possible to get descent results with STL-10 or similar datasets if you were to use a more complex autoencoder?  If a more sophisticated autoencoder such as a UNET or Densenet with more dimensions in the embedding layer is successfully trained to reproduce STL-10 images, can you effectively use this for DCEC?

**Comment by vivektreddy** [comment]
Hi, great paper!
I am wondering if it would be possible to get descent results with STL-10 or similar datasets if you were to use a more complex autoencoder? If a more sophisticated autoencoder such as a UNET or Densenet with more dimensions in the embedding layer is successfully trained to reproduce STL-10 images, can you effectively use this for DCEC?
