### ISSUE TITLE
Doesn't exist the link of USPS

### ISSUE THREAD

**Issue by leo2105** [XifengGuo/DCEC#7]
I have the next message when I run 

> bash ./download_usps.sh 

--2019-11-01 17:07:48--  http://www-i6.informatik.rwth-aachen.de/~keysers/usps_train.jf.gz
Resolvendo www-i6.informatik.rwth-aachen.de (www-i6.informatik.rwth-aachen.de)... 137.226.36.140
Conectando-se a www-i6.informatik.rwth-aachen.de (www-i6.informatik.rwth-aachen.de)|137.226.36.140|:80... conectado.
A requisição HTTP foi enviada, aguardando resposta... 404 Not Found
2019-11-01 17:07:49 ERRO 404: Not Found.

gunzip: can't stat: usps_train.jf.gz (usps_train.jf.gz.gz): No such file or directory
--2019-11-01 17:07:49--  http://www-i6.informatik.rwth-aachen.de/~keysers/usps_test.jf.gz
Resolvendo www-i6.informatik.rwth-aachen.de (www-i6.informatik.rwth-aachen.de)... 137.226.36.140
Conectando-se a www-i6.informatik.rwth-aachen.de (www-i6.informatik.rwth-aachen.de)|137.226.36.140|:80... conectado.
A requisição HTTP foi enviada, aguardando resposta... 404 Not Found
2019-11-01 17:07:50 ERRO 404: Not Found.

gunzip: can't stat: usps_test.jf.gz (usps_test.jf.gz.gz): No such file or directory

**Comment by XifengGuo** [comment]
@leo2105 https://github.com/XifengGuo/IDEC/files/1613386/usps.zip

**Comment by ReemAli11** [comment]
what are the changes that should be done to .sh file to include the dataset. Also, there is a MINST-FULL and MINST-TEST
