### ISSUE TITLE
Algorithm converges when all samples belong to one cluster?

### ISSUE THREAD

**Issue by vivektreddy** [XifengGuo/DCEC#8]
When looking at the counts in each cluster after each update interval, iterations keep continuing until one giant cluster remains or there a few clusters but empty clusters. 
Does this always happen?  Is the key stopping the algorithm at a good point before this happens?
( I am working with 2D image data. )
Thank you.

**Comment by XifengGuo** [comment]
@vivektreddy 
I admit this problem does happen sometimes.
This algorithm depends on the performance of pretraining.
So it is better to tune the network structure and pretraining parameters for your own dataset.
If the problem still exists, you should stop the algorithm earlier according to some heuristics.
